# Generated by Django 3.0.3 on 2020-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('english_dob', models.DateField()),
                ('nepali_dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('admission_for_grade', models.CharField(max_length=50)),
                ('last_school', models.CharField(blank=True, max_length=255, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=15)),
                ('father_office', models.CharField(blank=True, max_length=250, null=True)),
                ('father_office_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(max_length=100)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_office', models.CharField(blank=True, max_length=250, null=True)),
                ('mother_office_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('local_name', models.CharField(blank=True, max_length=100, null=True)),
                ('local_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('local_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('local_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('local_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('local_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('bus_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('bus_pickup', models.CharField(blank=True, max_length=250, null=True)),
                ('disease_details', models.TextField(blank=True, null=True)),
                ('medication_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
