# Generated by Django 3.0.1 on 2020-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='father_office',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='admissionform',
            name='last_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
