# Generated by Django 3.0.1 on 2020-01-28 08:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_headline', models.CharField(max_length=250)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('notice_image', models.ImageField(upload_to='notices')),
                ('notice', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Notices',
            },
        ),
    ]
