# Generated by Django 3.0.1 on 2020-01-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='slug',
            field=models.SlugField(default='test'),
        ),
    ]
