# Generated by Django 3.0.1 on 2020-01-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_notices_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='slug',
            field=models.SlugField(),
        ),
    ]
