# Generated by Django 3.0.1 on 2020-01-31 16:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200128_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEOMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Message From CEO',
                'verbose_name_plural': 'Message From CEO',
            },
        ),
    ]
