# Generated by Django 3.0.1 on 2020-01-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_ceomessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_author', models.CharField(max_length=30)),
                ('testimonial_desgination', models.CharField(max_length=100)),
                ('testimonial_picture', models.ImageField(upload_to='testimonials')),
                ('testimonial_text', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimonials',
            },
        ),
    ]
