# Generated by Django 3.0.1 on 2020-01-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_testimonials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonials',
            old_name='testimonial_desgination',
            new_name='testimonial_designation',
        ),
    ]
