# Generated by Django 3.0.1 on 2020-01-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='important')),
                ('url', models.CharField(default='#', max_length=300)),
                ('notice_title', models.CharField(max_length=100)),
            ],
        ),
    ]
