# Generated by Django 3.0.1 on 2020-02-01 03:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_importantnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='section_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='ceomessage',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='notices',
            name='notice',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
