# Generated by Django 3.0.1 on 2020-02-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_downloads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.AlterModelOptions(
            name='downloads',
            options={'verbose_name_plural': 'Downloads'},
        ),
    ]
