# Generated by Django 3.0.1 on 2020-02-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='background_image',
            field=models.ImageField(blank=True, upload_to='background'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='preloader',
            field=models.ImageField(blank=True, upload_to='preloader'),
        ),
    ]
