# Generated by Django 3.0.1 on 2020-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20200421_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('Nursery', 'Nursery'), ('KG', 'KG'), ('One', 'One'), ('Two', 'Two'), ('Three', 'Three'), ('Four', 'Four'), ('Five', 'Five'), ('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight'), ('Nine', 'Nine'), ('Ten', 'Ten')], max_length=10)),
                ('student_name', models.CharField(max_length=100)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_email', models.EmailField(max_length=254)),
                ('parent_phone', models.CharField(max_length=14)),
            ],
        ),
    ]
