# Generated by Django 3.0.1 on 2020-04-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20200214_1645'),
        ('school', '0015_teammember'),
    ]

    operations = [
    ]
